### ISSUE TITLE
Is this still working

### ISSUE THREAD

**Issue by gerardsyd** [wandaweb/Fooocus-Kaggle#1]
Hi - thanks for the notebook, super handy. Is this still working for you? I seem to be getting errors running this when running the ngrok / pinngy cells although the error seems to be in fooocus. A look through fooocus seems to suggest it has to do with the upgraded version but I've tried following those steps and it seems the error is at the kaggle end. Any ideas? Thanks!

```
stderr: ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.10/site-packages/Jinja2-3.1.2.dist-info/METADATA'


CMD Failed requirements: install -r "requirements_versions.txt"
Failed to load config key: {"path_sam": "/kaggle/working/Fooocus/models/sam"} is invalid or does not exist; will use {"path_sam": "../models/sam/"} instead.
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Total VRAM 16269 MB, total RAM 32110 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 Tesla P100-PCIE-16GB : native
VAE dtype: torch.float32
Traceback (most recent call last):
  File "/kaggle/working/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/kaggle/working/Fooocus/launch.py", line 152, in <module>
    from webui import *
  File "/kaggle/working/Fooocus/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/kaggle/working/Fooocus/modules/async_worker.py", line 3, in <module>
    from extras.inpaint_mask import generate_mask_from_image, SAMOptions
  File "/kaggle/working/Fooocus/extras/inpaint_mask.py", line 8, in <module>
    from rembg import remove, new_session
  File "/opt/conda/lib/python3.10/site-packages/rembg/__init__.py", line 5, in <module>
    from .bg import remove
  File "/opt/conda/lib/python3.10/site-packages/rembg/bg.py", line 17, in <module>
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
  File "/opt/conda/lib/python3.10/site-packages/pymatting/__init__.py", line 2, in <module>
    from pymatting.util import *
  File "/opt/conda/lib/python3.10/site-packages/pymatting/util/__init__.py", line 3, in <module>
    from pymatting.util.boxfilter import boxfilter
  File "/opt/conda/lib/python3.10/site-packages/pymatting/util/boxfilter.py", line 1, in <module>
    from pymatting.util.util import apply_to_channels
  File "/opt/conda/lib/python3.10/site-packages/pymatting/util/util.py", line 3, in <module>
    import scipy.sparse
  File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/__init__.py", line 307, in <module>
    from . import csgraph
  File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/csgraph/__init__.py", line 187, in <module>
    from ._laplacian import laplacian
  File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/linalg/__init__.py", line 140, in <module>
    from . import isolve, dsolve, interface, eigen, matfuncs
  File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/linalg/isolve/__init__.py", line 4, in <module>
    from .iterative import *
  File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/linalg/isolve/iterative.py", line 11, in <module>
    from .utils import make_system
  File "/opt/conda/lib/python3.10/site-packages/scipy/sparse/linalg/isolve/utils.py", line 7, in <module>
    from scipy.sparse.sputils import asmatrix
ImportError: cannot import name 'asmatrix' from 'scipy.sparse.sputils' (/opt/conda/lib/python3.10/site-packages/scipy/sparse/sputils.py)
```

**Comment by Natibliss** [comment]
Were you able to solve the problem? I have the same error.
